import Head from 'next/head';

type LayoutProps = {
  title: string;
  description?: string;
  children: React.ReactNode;
};

function Layout({ title = 'Polls', description = 'Generated by create next app', children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content={description} />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex flex-col min-h-screen bg-white'>
        <header className='flex justify-center items-center h-16 border-b'>
          <h1 className='text-2xl'>Polls</h1>
        </header>
        <main className='flex-1'>{children}</main>
      </div>
    </>
  );
}

export default Layout;
