import Head from 'next/head';
import Header from './Header';
import Wrapper from './Wrapper';

type LayoutProps = {
  title: string;
  description?: string;
  children: React.ReactNode;
};

function Layout({ title = 'Polls', description = 'Generated by create next app', children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content={description} />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Wrapper>
        <Header />
        <main className='grid flex-1'>{children}</main>
      </Wrapper>
    </>
  );
}

export default Layout;
